cargo-features = ["profile-rustflags"]

[package]
name = "custom-print-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "lib.rs"

[dependencies]
libc = "0.2"
custom-print = "0.1.0"

[dependencies.sea]
path = "../../sea-lib"
default-features = true
features = []